export default {
    avatarCell:{
        backgroundSize: 'cover',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: 'center',
        width:'33px',
        height:'33px',
        position:'relative',
        float:'left',
        borderRadius:'50%',
        display:'block',
    },
  button:{
      width:"100%",
      borderTopColor: '#E0BA51',
      borderRightColor: '#805D2C',
      borderBottomColor: '#E0BA51',
      borderLeftColor: '#e3ca86',
      borderWidth:' 4px 3px 4px 3px',
      borderStyle: 'solid',
      WebkitBorderRadius: '1px',
      MozBorderRadius: '1px',
      borderRadius: '1px',
      fontSize:'100%',
      boxSizing: 'border-box',
      padding: '4px 0px',
      fontFamily:'arial, helvetica, sans-serif',
      textDecoration:'none',
      display:'inline-block',
      textShadow:'-2px -2px 0 rgba(0,0,0,0.3)',
      fontWeight:'bold',
      color:'#FFFFFF',
      textAlign: 'center',
      backgroundColor: '#805D2C',
      backgroundImage: '-webkit-gradient(linear, left top, left bottom, from(#735327), to(#473419))',
      WebkitBorderImage: '-webkit-linear-gradient(left, #FE2EF7, #4AC0F2) 0 0 20px',
  },
    accountButton:{
        width:"100%",
        borderTopColor: '#E0BA51',
        borderRightColor: '#805D2C',
        borderBottomColor: '#E0BA51',
        borderLeftColor: '#e3ca86',
        borderWidth:' 4px 3px 4px 3px',
        borderStyle: 'solid',
        WebkitBorderRadius: '1px',
        MozBorderRadius: '1px',
        borderRadius: '1px',
        fontSize:'100%',
        boxSizing: 'border-box',
        fontFamily:'arial, helvetica, sans-serif',
        textDecoration:'none',
        display:'inline-block',
        textShadow:'-2px -2px 0 rgba(0,0,0,0.3)',
        fontWeight:'bold',
        color:'#FFFFFF',
        textAlign: 'center',
        backgroundColor: '#805D2C',
        backgroundImage: '-webkit-gradient(linear, left top, left bottom, from(#735327), to(#473419))',
        WebkitBorderImage: '-webkit-linear-gradient(left, #FE2EF7, #4AC0F2) 0 0 20px',
    }
};
