export const EDIT_ENTITY = 'EDIT_ENTITY';
export const ADD_ENTITY = 'ADD_ENTITY';
export const SHOW_ENTITY = 'SHOW_ENTITY';
export const DISABLE_ENTITY_PANEL = 'DISABLE_ENTITY_PANEL';
export const SET_RELATED_ENTITY = 'SET_RELATED_ENTITY';
export const SHOW_ENTITY_PANEL = 'SHOW_ENTITY_PANEL';