export const SET_PAGE_REQUEST= 'SET_PAGE_REQUEST';
export const SET_PAGE_REQUEST_SIZE_AND_NUMBER= 'SET_PAGE_REQUEST_SIZE_AND_NUMBER';
export const SET_PAGE_NUMBER= 'SET_PAGE_NUMBER';
export const SET_SEARCH_CRITERIA= 'SET_SEARCH_CRITERIA';
export const SET_PAGE_REQUEST_SORT_PROPERTIES= 'SET_PAGE_REQUEST_SORT_PROPERTIES';
