export const SHOW_LOGIN_PANEL = 'SHOW_LOGIN_PANEL';
export const SHOW_FORGOT_CREDENTIALS_PANEL = 'SHOW_FORGOT_CREDENTIALS_PANEL';
export const SHOW_REGISTER_PANEL = 'SHOW_REGISTER_PANEL';
export const SHOW_RESEND_MAIL_PANEL = 'SHOW_RESEND_MAIL_PANEL';
export const SHOW_CHANGE_PASSWORD_PANEL = 'SHOW_CHANGE_PASSWORD_PANEL';
