import {StyleSheet, css} from 'aphrodite';

const styles = {
  navigationBar:{
    margin:'0',
    marginTop:'20px',
    position:'relative',
    width:'90%',
    marginLeft:'5%',
    paddingBottom:'10px',
  },
  pageOptionsBar:{
    position:'relative',
    display:'inline-block',
    width:'100%',
    height:'auto',
    textAlign:'center',
  },
  navigatorButtonArrow:{
    width:'8%',
    minHeight:'32px',
    position:'relative',
    float:'left',
    background:'#473419',
    color:'rgb(189, 185, 189)',
    border:'1px solid rgb(64, 62, 63)',
    boxShadow:'inset 0 0 4px #9c7239',
    outline:'none',
  },
  goldAndBrownTheme:{
    boxSizing:'border-box',
    border:'1px solid',
    color:'rgb(218, 188, 109)',
    borderTopColor: '#E0BA51',
    borderBottomColor: '#614722',
    borderRightColor: '#805D2C',
    borderLeftColor: '#e3ca86',
  },
  navigatorInput:{
    boxSizing:'border-box',
    position:'relative',
    width:'8%',
    height:'100%',
    height:'auto',
    paddingTop:"5px",
    paddingBottom:'5px',
    background:'white',
    display:'inline-block',
    backgroundColor:'lightgrey',
    textAlign:'center',
    border:'1px solid grey',
  },
  navigatorLabel:{
    boxSizing:'border-box',
    position:'relative',
    width:'16%',
    height:'100%',
    paddingTop:"3px",
    paddingBottom:'3px',
    background:'white',
    display:'inline-block',
    marginLeft:'1%',
    border:'1px solid',
    color:'rgb(218, 188, 109)',
    borderTopColor: '#E0BA51',
    borderBottomColor: '#614722',
    borderRightColor: '#805D2C',
    borderLeftColor: '#e3ca86',
    background:'#473419',
    boxShadow:'inset 0 0 4px #9c7239',
},
  navigatorButton:{
    boxSizing:'border-box',
    marginRight:'1%',
    position:'relative',
    display:'inline-block',
    border:'1px solid',
    color:'rgb(218, 188, 109)',
    borderTopColor: '#E0BA51',
    borderBottomColor: '#614722',
    borderRightColor: '#805D2C',
    borderLeftColor: '#e3ca86',
    background:'#473419',
    paddingTop:"5px",
    paddingBottom:'5px',
    outline:'none',
    boxShadow:'inset 0 0 4px #9c7239',
  },
  pager:{
    boxSizing:'border-box',
    position:'relative',
    display:'inline-block',
    background: '#EEE',
    minWidth: '10px',
    whiteSpace:'nowrap',
    paddingBottom:"6px",
    background:'rgb(218, 188, 109)',
  },
  container:{
    boxSizing:'border-box',
    marginTop:'1px',
    textAlign:'center',
    position:'relative',
    display:'inline-block',
    width:'100%',
    textAlign:'center',
    overflow:'hidden',
    float:'left',
  },
  pageButton:{
    boxSizing:'border-box',
    background:'#473419',
    color:'rgb(189, 185, 189)',
    border:'1px solid rgb(64, 62, 63)',
    height:'24px',
  },
}

const resp = StyleSheet.create({

  navigatorButtonArrow:{
    ':hover':{
        borderTopColor: 'rgb(249, 249, 249)',
        borderBottomColor: 'rgb(204, 126, 69)',
    },
    ':active':{
        color:'lightGrey',
        borderTopColor: 'rgb(204, 126, 69)',
        borderBottomColor: 'rgb(249, 249, 249)',
      },
  },
  navigatorButton:{
    ':hover':{
        borderTopColor: 'rgb(249, 249, 249)',
        borderBottomColor: 'rgb(204, 126, 69)',
    },
    ':active':{
        color:'lightGrey',
        borderTopColor: 'rgb(204, 126, 69)',
        borderBottomColor: 'rgb(249, 249, 249)',
      },
  },
})


export {resp, styles};
